### ISSUE TITLE
Broken link windows 64 bits

### ISSUE THREAD

**Issue by YBJair** [apelegri/wechat-miniprogram-whitebook#11]
The Windows 64-bit Devtools link is broken, it points to the MacOS version, rather than the 64-bit windows version.

Under WeChat IDE -> What's This -> Download the WeChat IDE here: Mac, Windows 64

I just copy/pasted an old issue that was closed without being resolve.

**Comment by mcpi** [comment]
Try this link: https://servicewechat.com/wxa-dev-logic/download_redirect?type=x64&from=mpwiki
I've made a fix, and asked for it to be pulled in. So, hopefully it'll be fixed soon.

**Comment by apelegri** [comment]
Sorry for that, Done.
