### ISSUE TITLE
Develop WeChat miniprogram for startups

### ISSUE THREAD

**Issue by tarvos21** [apelegri/wechat-miniprogram-whitebook#7]
Hi there, sorry if it's annoying, I am a Chinese developer, and specialize in WeChat miniprogram, if any startup wants to develop your own mini program on WeChat platform(why not? 1 billion users there), definitely I can help you. Contact me through my email: tarvos21@gmail.com, hope to hear from you.

**Comment by haxpor** [comment]
I don't think this is the right place to promote or advertise your business.
